### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by ronaldpan** [sgsellan/gpytoolbox#148]
When I run "python -m pip install gpytoolbox",
Collecting gpytoolbox
  Using cached gpytoolbox-0.3.2.tar.gz (2.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy<2 in /root/anaconda3/envs/breaking-bad/lib/python3.8/site-packages (from gpytoolbox) (1.24.3)
Requirement already satisfied: scipy in /root/anaconda3/envs/breaking-bad/lib/python3.8/site-packages (from gpytoolbox) (1.10.1)
Collecting scikit-image (from gpytoolbox)
  Using cached scikit_image-0.21.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Collecting networkx>=2.8 (from scikit-image->gpytoolbox)
  Using cached networkx-3.1-py3-none-any.whl.metadata (5.3 kB)
Collecting pillow>=9.0.1 (from scikit-image->gpytoolbox)
  Using cached pillow-10.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
Collecting imageio>=2.27 (from scikit-image->gpytoolbox)
  Using cached imageio-2.35.1-py3-none-any.whl.metadata (4.9 kB)
Collecting tifffile>=2022.8.12 (from scikit-image->gpytoolbox)
  Using cached tifffile-2023.7.10-py3-none-any.whl.metadata (31 kB)
Collecting PyWavelets>=1.1.1 (from scikit-image->gpytoolbox)
  Using cached PyWavelets-1.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.9 kB)
Requirement already satisfied: packaging>=21 in /root/anaconda3/envs/breaking-bad/lib/python3.8/site-packages (from scikit-image->gpytoolbox) (24.1)
Collecting lazy_loader>=0.2 (from scikit-image->gpytoolbox)
  Using cached lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
Using cached scikit_image-0.21.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.9 MB)
Using cached imageio-2.35.1-py3-none-any.whl (315 kB)
Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)
Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Using cached pillow-10.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
Using cached PyWavelets-1.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.9 MB)
Using cached tifffile-2023.7.10-py3-none-any.whl (220 kB)
Building wheels for collected packages: gpytoolbox
  Building wheel for gpytoolbox (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for gpytoolbox (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [196 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/tip_angles_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/quadtree_gradient.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/signed_distance_polygon.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h0inv.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/ray_mesh_intersect.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/stochastic_poisson_surface_reconstruction.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/tip_angles.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/catmull_rom_spline.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/barycenters.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/particle_swarm.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/grad_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/apply_colormap.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/colormap.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/triangle_triangle_distance.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/grad.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/biharmonic_energy.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/cotangent_weights_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h0inv_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/doublearea.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/decimate.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/volume.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/biharmonic_energy_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/quadtree_boundary.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/non_manifold_edges.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/bad_quad_mesh_from_quadtree.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/ray_box_intersect.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/remove_unreferenced.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/rotation_matrix_from_vectors.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/fd_grad.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_d1.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/traverse_aabbtree.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h1_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/png2poly.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/reach_for_the_spheres.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/edges.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/per_vertex_normals.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h0_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/in_quadtree.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/boundary_edges.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/cone.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/connected_components.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/boundary_loops.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/barycentric_coordinates.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/edge_indices.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/halfedge_lengths.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/fast_winding_number.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/boundary_vertices.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/squared_exponential_kernel.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/cotangent_weights.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/winding_number.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/normalize_points.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/fd_partial_derivative.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h1inv_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/adjacency_matrix.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/quadtree_laplacian.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/reach_for_the_arcs.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/ray_polyline_intersect.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/subdivide_quad.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/offset_surface.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h2.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/cotangent_laplacian_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/boundary_faces.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/read_dmat.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/grid_neighbors.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/compactly_supported_normal.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/initialize_quadtree.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/point_cloud_to_mesh.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/initialize_aabbtree.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/fd_interpolate.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/faces.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/array_correspondence.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/angle_defect.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/icosphere.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/halfedge_edge_map.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h2inv.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_d0.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/triangle_triangle_adjacency.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/marching_cubes.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/remove_duplicate_vertices.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/read_mesh.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/write_mesh.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h0.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/min_quad_with_fixed.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/halffaces.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/compactly_supported_normal_kernel.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/gaussian_process.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/minimum_distance.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/fixed_dof_solve.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/ray_triangle_intersect.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/regular_circle_polyline.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/halfedges.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/regular_cube_mesh.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/quadtree_children.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/in_element_aabb.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/remesh_botsch.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/halfedge_lengths_squared.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/metropolis_hastings.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/massmatrix.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/cotangent_laplacian.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h2inv_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h1.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/linear_elasticity.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/torus.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/upper_envelope.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/cut_edges.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/squared_distance.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/random_points_on_mesh.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/signed_distance.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/linear_elasticity_stiffness.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/__init__.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/angle_defect_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h2_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/matrix_from_function.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/regular_square_mesh.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/subdivide.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/dec_h1inv.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/edge_edge_distance.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/per_face_normals.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/linear_blend_skinning.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/cylinder.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/squared_distance_to_element.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/marching_squares.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/massmatrix_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/grid_laplacian_eigenfunctions.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/doublearea_intrinsic.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      copying src/gpytoolbox/approximate_hausdorff_distance.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox
      creating build/lib.linux-x86_64-cpython-38/gpytoolbox/copyleft
      copying src/gpytoolbox/copyleft/swept_volume.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox/copyleft
      copying src/gpytoolbox/copyleft/mesh_boolean.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox/copyleft
      copying src/gpytoolbox/copyleft/lazy_cage.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox/copyleft
      copying src/gpytoolbox/copyleft/do_meshes_intersect.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox/copyleft
      copying src/gpytoolbox/copyleft/__init__.py -> build/lib.linux-x86_64-cpython-38/gpytoolbox/copyleft
      running build_ext
      CMake Warning:
        Ignoring extra path from command line:

         "/tmp/pip-install-r_kkdfwq/gpytoolbox_3f9a081586fb4ca397ecc7e8a49e131a"

      CMake Error: The source directory "/tmp/pip-install-r_kkdfwq/gpytoolbox_3f9a081586fb4ca397ecc7e8a49e131a" does not appear to contain CMakeLists.txt.
      Specify --help for usage, or press the help button on the CMake GUI.
      /tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      Running cmake configure command: cmake /tmp/pip-install-r_kkdfwq/gpytoolbox_3f9a081586fb4ca397ecc7e8a49e131a -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-r_kkdfwq/gpytoolbox_3f9a081586fb4ca397ecc7e8a49e131a/build/lib.linux-x86_64-cpython-38 -DPYTHON_EXECUTABLE=/root/anaconda3/envs/breaking-bad/bin/python -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
      Traceback (most recent call last):
        File "/root/anaconda3/envs/breaking-bad/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/anaconda3/envs/breaking-bad/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/anaconda3/envs/breaking-bad/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 421, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 128, in <module>
        File "<string>", line 106, in main
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-dqn9i7zr/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "<string>", line 41, in run
        File "<string>", line 84, in build_extension
        File "/root/anaconda3/envs/breaking-bad/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-r_kkdfwq/gpytoolbox_3f9a081586fb4ca397ecc7e8a49e131a', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-r_kkdfwq/gpytoolbox_3f9a081586fb4ca397ecc7e8a49e131a/build/lib.linux-x86_64-cpython-38', '-DPYTHON_EXECUTABLE=/root/anaconda3/envs/breaking-bad/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gpytoolbox
Failed to build gpytoolbox
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (gpytoolbox)

**Comment by sgsellan** [comment]
Thank you very much for submitting this issue! I have never encountered this before. Could you please:

- Let us know what your operating system is?
- Let us know if this issue happens for every version of gpytoolbox, i.e., does this happen if you do `pip install gpytoolbox==0.3` _and_ `pip install gpytoolbox==0.2` _and_ `pip install gpytoolbox==0.1`?

**Comment by ronaldpan** [comment]
pip install gpytoolbox==0.2.0 is OK.
I do not try pip install gpytoolbox==0.3.0 and pip install gpytoolbox==0.1

**Comment by XinwenDing** [comment]
Hi Silvia! Here is a another data point. I'm working on a Ubuntu 20.04 + python 3.8. 
gpytoolbox==0.3.x do not work for me. I finally go with gpytoolbox==0.2.0.

**Comment by sgsellan** [comment]
Hi all! Could you please try the newest version, and see if this issue is fixed?

**Comment by XinwenDing** [comment]
I just changed my laptop from PC to mac. I'm able to install the latest version on my mac. Not sure how things work on the PC side. Thank you very much Silvia!

**Comment by zoemarschner** [comment]
I found that I run into the same error described above in python version 3.13 (pip version 25.0.1, gpytoolbox versions 0.3.3, 0.3, 0.2, 0.1 all fail, MacOS), but downgrading to python version 3.12 works. I have also tested that versions 3.10 and 3.11 work. My labmate also ran into the same error when trying to install the latest gpytoolbox release with pip in python 3.13 on her Mac, while my labmates that have python <=3.12 are able to install it with no problems.

**Comment by sgsellan** [comment]
Hi Zoe, I believe that is correct and expected, as we only built wheels for gpytoolbox up to 3.12. Good to know though, thanks!

**Comment by sgsellan** [comment]
Hi all! I believe all these issues are fixed now, and support for python 3.13 will be included in version 0.3.5 (see #161 ), so I am closing this issue. Feel free to reopen if you run into any other issues or anything in this thread has not been resolved!
